### ISSUE TITLE
Pomf can be used as an XSS attack vector via .svg

### ISSUE THREAD

**Issue by otter1412** [nokonoko/Pomf#41]
It looks like most or all sites running the pomf software can be used as a XSS attack vector via the .svg file format.
I think the only way to fix is to strip all unnecessary html with in the file, or ban .svg all together.
Proof of Concept:
http://a.pomf.cat/zgeuli.svg
http://b.1339.cf/ukzceyr.svg
http://my.mixtape.moe/brbuhb.svg

**Comment by BrofessionalBrogrammer** [comment]
Verified for http://maxfile.ro/ as well.

**Comment by otter1412** [comment]
and https://i.pantsu.cat/jtbpkl.svg
pansu.cat

**Comment by alin1337** [comment]
I come from maxfile with the following question:
How is an xss attack going to affect my server since there are no cookies/no sessions on hosting domain?

**Comment by otter1412** [comment]
I should probably fix the title, attack vector is more accurate, sorry. there could be some repercussions like the imgur/8chan thing.

**Comment by otter1412** [comment]
@alin1337 
It really won't be affected, just could be blamed for hosting the exploit if it is used as an attack vector.
I'm sorry for being bad at this.

**Comment by BrofessionalBrogrammer** [comment]
An example of something that could be malicious if hosted on a pomf clone as an svg. Obviously the attacks could be much worse, but just a proof of concept. 

WARNING: DO NOT RUN 

```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
  <polygon id="triangle" points="0,0 0,50 50,0" fill="#009900" stroke="#004400"/>
  <script language="javascript" type="text/javascript">
    var foo = "bar";
    while (1) {
    foo = foo += "bar"; // fills memory, then crashes
    }
  </script>
</svg>
```

**Comment by Drybones5** [comment]
I disabled .SVG uploads on https://mixtape.moe for the time being

I let at least pantsu.cat know. Here is his response on his behalf.

10:06:47 WubTheCaptain | This is a browser level issue, not a Pomf one. At most, it's an issue with not implementing CSP on server.
10:07:09 WubTheCaptain | Feel free to post a comment on GitHub about my opinion (on behalf of Pantsu.cat)
0:07:16 Drybones | Not a pomf issue, sure, but I'm not letting mixtape be blacklisted or accused for a XSS attack
10:07:36 WubTheCaptain | That's your decision, but in my opinion a poor one

I'll let pomf.cat know next

**Comment by WubTheCaptain** [comment]
Honestly, this is not an issue in Pomf. Take it to the browser vendors, or webmasters not implementing CSP. I have no intention to fix this in Pantsu.cat's fork of Pomf, but at most recommend ewhal to implement Content-Security-Policy on the webserver.

You could always upload a .html file on Pomf.se. neku implemented CSP briefly, but then people complained their hosted pages would break and reverted the change to be less secure. You can also iframe those HTML pages.

I personally hope Pomf clones will remain allowing .SVG files to be uploaded.

TL;DR: wontfix from me.

**Comment by otter1412** [comment]
@WubTheCaptain It's your choice man, I'm just informing the right people.

**Comment by nokonoko** [comment]
I agree with Wub on this one, maybe we should create a recommended CSP?

**Comment by WubTheCaptain** [comment]
@nokonoko It doesn't matter if you have no CSP, strict CSP or lax CSP, you can still XSS yourself because CSP can be defeated on Pomf (upload both `.html` and `.js` files). The only workaround is to use `script-src 'none'`, but it's too breaking and no sites really do this in practice. I would assume even GitHub pages allows you to XSS yourself, any webhost does really.

The title of this issue is misleading. JavaScript embedded in SVG is not executed when the SVG image is embedded on a HTML page in modern browsers. Proof of concept: <https://my.mixtape.moe/pbwpva.html> (no CSP) and <https://i.pantsu.cat/hpshqc.html> (CSP). Third-party websites are unaffected.

After some conversation, other clones like 1339.cf have also agreed this to be a non-issue.

    16:11:00     bohrmeista | what's all this XSS mess?
    16:11:19     bohrmeista | isn't it just people noticing they can embed JS into websites as well as into SVGs?
    16:11:40     bohrmeista | which would then be a browser problem because they parse JS inside SVGs
    16:11:53     bohrmeista | god I hate those internet nerds
    16:12:06     bohrmeista | wsgy from bugged me about it all day
    16:12:17     bohrmeista | "FIX IT IN YOA POMF CODE"
    16:12:20     bohrmeista | no

Sending SVG/HTML files as `text/plain` is an option, but in my opinion this is also too breaking and no sites do this in practice. Fundamentally, it's a problem in browsers. The real solution: Don't go to shady pages hosted on shady sites with JavaScript enabled, including `.html` files hosted on Pomf clones.

Stil, as the best practice you should implement CSP on any Pomf clone to prevent some other forms of XSS/CSRF. But that won't be discussed here, and it's not Pomf related.

I argued about this on IRC for two hours and I'm sick of it. There's no issue, and Pomf doesn't need to recommend any specific CSP rule.

> 16:14:58     bohrmeista | I learned that people do a lot to feel like a 1337 haxxor discovering the next ebin security exploit

**Comment by NuckChorris** [comment]
Standard pomf sites don't have cookies or logins, this isn't an issue. If you add logins, use tokens instead of cookies or move file serving to a separate cookieless domain

**Comment by WubTheCaptain** [comment]
@otter1412 You already deleted your account, but I'd like to say now the title is even more misleading and assumes Pomf should allow XSS attacks. This contradicts the conversation in this ticket.

**Comment by alin1337** [comment]
@NuckChorris You tell them dude. XSS is not a real attack.

**Comment by BrofessionalBrogrammer** [comment]
I'll be using and reccomending mixtape.moe from now on. Kind of a shame you guys couldn't at the very least strip the script tags out of svg files. Bad business move more than anything, but if you want to leave security issues open that's on you guys. There's always alternatives.

**Comment by Drybones5** [comment]
@BrofessionalBrogrammer I recently re-enabled .SVG file uploads after the discussions here.

I would like to actually strip the HTML of .SVG files though. but are you suggesting I keep AVG disabled?

**Comment by BrofessionalBrogrammer** [comment]
@Drybones5 I would just strip the <script> tags out of .SVG files, as they seem to be the main issue here. People are starting to abuse it, I've seen a few threads on various image boards of people using this since last night.

**Comment by WubTheCaptain** [comment]
@Drybones5 Stripping HTML from SVG is doing more harm than you actually want to. If you don't want JavaScript executed on uploaded SVG files, use Content Security Policy directive `script-src 'none'`. It is a much simpler solution and preserves the original source of the uploaded file. I don't see point in doing this for reasons mentioned earlier.

If you go ahead with stripping HTML from `.svg` though, be sure to strip HTML from `.html` because that's also harmful for you. Be sure to do regex on all uploads for EICAR text files too, that may trigger someone's anti virus which is a Bad Thing™. And make sure to add a warning to the developer console in your browser, you may also self-XSS yourself from there. (See my sarcasm, although Facebook actually implemented the developer console warning.)

To prove my point, as I and others have already exclaimed here, this is a non-issue and there are much better ways to mitigate it if you are feeling it's somehow making you feel more secure when it really isn't. You're just breaking features which work as designed.

@BrofessionalBrogrammer Feel free to show some actual examples where this is an issue. Chrome `>= 25` and Firefox `>= 23` support CSP as per standard, but CSP was first implemented in Firefox `4`. I don't know about Internet Explorer.

I was about to say what @NuckChorris already exclaimed, but that can be mitigated. This issue was known 1 year 2 months ago on Pomf.se too, but mostly ignored.

If you want to search for a real XSS attack, I recommend someone with moe panel should check if the `strip_tags` patch that was applied in commit `de0b847` is actually working with something like `<b<b>> test </b<b>>` original filenames.

**Comment by Drybones5** [comment]
Someone going to an HTML file on mixtape usually has the sense to understand the risk of visiting the link. Someone visiting a link to view an .svg file doesn't expect Javascript to be executed.

**Comment by BrofessionalBrogrammer** [comment]
@WubTheCaptain I'm running Firefox 41.0.2 and ran the sample code I put above (after turning off noscript), it crashed my browser. Looks like people on image boards are starting to abuse it as well, I've seen 3 threads since last night. Mostly harmless stuff but in the right hands it could cause some damage.

**Comment by WubTheCaptain** [comment]
@Drybones5 The JavaScript in SVG doesn't get executed if you tell it not to, if you read my post again.

@BrofessionalBrogrammer Self-XSS is not a vulnerability.

**Comment by WubTheCaptain** [comment]
Sorry, correcting my terms. @BrofessionalBrogrammer Executing any JavaScript from a web page is not a vulnerability, it's a browser feature.

**Comment by BrofessionalBrogrammer** [comment]
@WubTheCaptain Yes, but in this particular case it's being used maliciously. It would be one thing if on some random website, but it's going to make people shy away from pomf clones. Check 8/b/ right now, theres 2 threads where people are using this.

**Comment by NuckChorris** [comment]
Feel free to XSS the shit out of Pomf, because you can't do fucking anything with it. There's no attack if there's nothing to attack

**Comment by WubTheCaptain** [comment]
@BrofessionalProgrammer You can use JavaScript maliciously and create malicious websites, that's not news. You can do this with any programming language. If you have an issue with it, don't run any code which means don't use a computer.

I'm done and sick of this. @nokonoko, I think you can do the right thing and have a final call on this.

**Comment by nokonoko** [comment]
I think it's up to the user running the Pomf clone if they want to block/scrub SVG files.
