### ISSUE TITLE
[feature request] show amount of files uploaded/hosted on homepage

### ISSUE THREAD

**Issue by jamiew0w** [nokonoko/Pomf#51]
I think the best way of doing this is via counting the rows in the db, rather than counting the files themselves. I'm pretty basic at PHP though and can't figure out the best way of doing it.

Also I'm not sure how much (if any) overhead this would add to the homepage. Could cache it via memcached etc but then we're straying a little from 'lightweight'.

Ideas? Is this worth being added?

**Comment by nokonoko** [comment]
Best way would be to count rows and periodically update it to reduce DB requests.

Don’t think I’ll add this tho, not really useful and more of a fun thing one could implement themselves.

**Comment by avail** [comment]
as neku said, one should probably implement this for themselves, as it does bring the lightweightedness down slightly, but, here's a simple implementation example:

imagine something like the following:
table `stats`:
id, key, value
1, enabled, 0
2, uploads, 69420

one could make it insert into said table on upload rather than use a periodic update script, but provide a script that would just bring the table up to date when ran from cli if it's a freshly updated install

web would just check if `enabled` is `1` and if so display the data somewhere.

**Comment by jamiew0w** [comment]
sounds good guys, thanks!
